Question: 
    Test 29 Hard FaultingI'm only failing Test 29 and I'm not sure what the reason could be. I've tried propagating the changes, I've set everything to reference the owner across all the files including sysfile, syscall, and vm. Does anyone have any suggestions/has encountered the same problem?lab3

    Student Answer: 
    I (not OP) solved this by making sure I correctly handle creating a thread from within a thread.

    Instructor Answer: 
    

    Followup Discussions:
    @602_f1Anonymous Calc3 weeks agoI'm facing the same issue - please let me know if you make any progress!0Anonymous Atom3 weeks agoI haven't been able to make any practice, did you figure anything out?0Anonymous Calc2 weeks agoJust discussed it with a TA at office hours and it turns out that it's most likely to do with creating a thread inside a thread. My code currently doesn't handle this case properly. Hopefully you have the same issue0
    